name: Sync with Upstream

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/CSCE331-Fall2024/project-3-team-3c.git # Replace with actual upstream URL

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Check for differences
        id: check_changes
        run: |
          git diff --quiet HEAD upstream/main || echo "::set-output name=changes::true"

      - name: Merge changes from upstream/main
        if: steps.check_changes.outputs.changes == 'true'
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push changes to origin
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/tannergz123/project-3-team-3c.git
          git push origin main
